### ISSUE TITLE
Dodanie encji Film

### ISSUE THREAD

**Issue by marcinkunert** [javastartpl/filmueb#2]
Film powinien posiadać takie pola jak:

- tytuł
- opis
- rok wydania
- odnośnik do obrazka z okładką

**Comment by swierka** [comment]
Hej, gdyby ktos sie zastanawiam to dodam nastepuje pola:
/**
 * @param year to rok produkcji
 * @param photo to URL do zdjęcia
 * @param id to id filmu nadawane automatycznie
 *
 * */
public class Movie {
    private String title;
    private String description;
    private String category;
    private int year;
    private String photo;
    private Long id=0L;
}
