### ISSUE TITLE
Ujednolicenie kontrolerów.

### ISSUE THREAD

**Issue by Victorarmy** [javastartpl/filmueb#24]
Proponuję ujednolicenie kontrolerów, ponieważ nie widzę sensu istnienia zarówno MovieControllera jednocześnie z FilmControllerem. Można to ładnie zrobić w jednym wszystko. Chyba, że ktoś ma z tym jakiś pomysł, którego profity pokażą się dopiero później to prosiłbym o wyjaśnienie :D

**Comment by mrwojciech** [comment]
Zmergowalem wszystko do FilmControler, prosze o merga do mastera.
