### ISSUE TITLE
Dodanie możliwości edycji filmu

### ISSUE THREAD

**Issue by marcinkunert** [javastartpl/filmueb#7]
Powinno się dać edytować tytuł, opis i datę wydania filmu.

**Comment by marcink76** [comment]
Biere! Tylko jak? ;)

**Comment by marcinkunert** [comment]
Najpierw musisz dołączyć do projektu. Link: https://github.com/javastartpl/filmueb/invitations
Następnie po prawej stronie u góry powinno być dostępne Assigness - tam możesz dodać siebie.
